version: '3.9'
services:
  # Create the database service
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'laravel-db'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_USER: '${DB_USERNAME:-laravel}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Create the php-apache service
  php-apache-environment:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 'triple3a/laravel-app'
    volumes:
      - .:/var/www/html/
      - ./storage:/var/www/html/storage
    ports:
      - "5000:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Create phpmyadmin service to view the database in the GUI
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "4000:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
      UPLOAD_LIMIT: 100M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
