---
- name: "Run Docker-Compose using ansible playbook"
  hosts: localhost
  tasks:
  - name: stop and remove containers
    command: sudo docker-compose down
    ignore_errors: yes

  # Make sure to change the image name with your personal dockerhub account and repository 
  - name: remove image built with dockercompose
    command: sudo docker rmi ghassan8080/laravel-app
    ignore_errors: yes

  - name: remove php-apache image
    command: sudo docker rmi php:8.2-apache
    ignore_errors: yes

  - name: remove mysql image
    command: sudo docker rmi mysql:8.0
    ignore_errors: yes

  - name: remove phpmyadmin image
    command: sudo docker rmi phpmyadmin/phpmyadmin:latest
    ignore_errors: yes

  - name: build docker-compose
    command: sudo docker-compose up -d --build

  - name: wait for database to be ready
    wait_for:
      port: 3306
      host: localhost
      timeout: 60

  # This task is to get into the apache container where the project file exist and run composer install command
  - name: Run composer install inside apache container
    command: sudo docker exec -i laravel-app_php-apache-environment_1 bash -c "composer install --no-dev --optimize-autoloader"

  - name: Run npm install and build assets inside apache container
    command: sudo docker exec -i laravel-app_php-apache-environment_1 bash -c "npm install && npm run build"

  - name: Set proper permissions
    command: sudo docker exec -i laravel-app_php-apache-environment_1 bash -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache"

  - name: Generate application key
    command: sudo docker exec -i laravel-app_php-apache-environment_1 bash -c "php artisan key:generate --force"
    ignore_errors: yes

  - name: Run database migrations
    command: sudo docker exec -i laravel-app_php-apache-environment_1 bash -c "php artisan migrate --force"
    ignore_errors: yes
